In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [7]:
df = pd.DataFrame(np.array([[5, 6, 8, 13, 19, 20, 24],[2, 5, 10, 22, 24, 31, 37],[7, 13, 14, 19, 21, 28, 31],[11,15,18,23,27,28,33],[1, 2, 5, 10, 13, 26, 34,],[3, 6, 12, 19, 20, 24, 28],[3 ,5, 19, 21, 26, 30, 35],[2, 5, 15 ,18, 20 ,29 ,30],[3, 4, 24, 25 ,28, 30 ,35],[1, 15 ,16, 21, 23, 28, 31],[7, 19, 23, 25, 28, 33, 34],[1, 13, 16, 22, 27, 35, 36],[2 ,8, 13, 20, 26, 29, 36],[8, 12, 13, 16, 20, 23, 27],[1 ,10, 17, 19, 23, 27, 34],[3, 5, 15, 20, 21, 30, 34],[2, 5, 7, 12, 14 ,18, 29],[7, 10, 16, 24, 25, 26, 31],[2, 3, 23, 27, 32, 34, 36],[12,16,22,25,29,30,35],[1, 8 ,14 ,26, 29, 31, 37],[11,12,15,17,21,30,33],[5, 12, 13, 15, 19, 32, 36],[3, 11, 12, 25, 27, 34, 36],[2, 15, 21, 23, 30, 31, 36],[13,14,16,22,25,28,37],[6 ,9 ,10, 11, 14, 15, 24],[1, 9 ,11, 16, 17, 22, 34],[1 ,9 ,12, 14, 18, 20, 26],[13,14,19,22,25,27,33],[12,14,18,19,23,28,31],[12,14,16,30,31,32,36],[3, 4, 7, 8, 12, 29, 37],[6, 12, 14, 15, 22, 26, 28],[4, 6, 10, 16, 22, 24, 28],[2, 7, 18, 22, 24, 34, 35],[1, 7, 9, 12, 21, 24, 37],[13,15,21,25,29,36,37],[4, 7, 10, 11, 18, 33, 34],[6, 7, 9, 10, 23 ,28,30],[5, 12, 13, 15, 27, 35, 37],[7, 14, 15, 22, 27, 29, 32],[5, 10, 12, 18, 24, 28, 34],[3,8, 14, 15, 24, 28, 29],[3,9, 20, 21, 24, 25, 28],[5,11, 12, 17, 20, 23, 29],[4,6, 9, 21, 25, 32, 37],[1,3, 5, 14, 17, 22, 35],[3,5, 6, 20, 22, 26, 28],[6,10, 13, 15, 22, 24, 37],[6, 10, 18, 19, 28, 30, 37],[1, 13, 14, 17, 21, 31, 37],[6, 18, 21, 22, 30, 35, 36],[6, 19, 21, 27, 29, 35, 36],[4, 20, 21, 23, 25, 31, 33],[2, 11, 12, 21, 27, 28, 37],[7, 9, 11, 13, 15, 18, 29],[1 ,4 ,12, 17, 24, 32, 36],[4, 7, 23, 27, 28, 29, 31],[4, 18, 23 ,25, 31, 32, 33],[15,24,27,29,30,34,35],[4, 10, 12, 17, 19, 21, 36],[9, 11, 15, 22, 24, 28, 37],[2, 6, 11, 15, 22 ,34, 37],[2, 10, 13, 17, 20, 24, 36],[4, 11, 16, 17, 19 ,25, 33],[6, 7, 13, 18, 26, 30, 33],[8, 9, 10, 11, 14, 22, 31],[2, 4, 5 ,6, 24, 26, 28],[9, 10, 11, 16, 18, 30, 34],[1, 3, 14, 15, 20, 30, 32],[1, 3, 10, 11, 31, 33, 35],[2, 11, 15, 17, 28, 30, 31],[4, 12 ,19 ,20 ,24, 32, 34],[2, 4, 7, 17, 20, 25, 34],[2 ,5 ,17 ,27, 33, 35, 37],[10,14,19,21,23,25,31],[3, 8, 17, 18, 22, 27, 34],[4, 6, 8 ,10, 12, 14, 16],[3, 6, 13, 27, 29, 33, 34],[11,12,17,20,25,28,37],[12,14,22,29,31,32,37],[3, 7, 12, 20, 25, 29, 31],[4, 11, 15, 16, 19, 22, 35],[7, 9, 12, 21, 30, 35, 36],[1, 7, 15, 17, 19, 22, 34],[4, 6, 7 ,11, 19, 23, 36],[6, 11, 12, 16, 19, 23, 35],[8, 12, 13, 14, 16, 27, 31],[1, 8, 10, 16, 23, 26, 33],[1, 8 ,13, 20 ,22, 29, 30],[1 ,4 ,6 ,11, 12, 28, 32],[5, 9, 12, 15, 23, 33, 36],[6, 11, 12, 21, 23, 26, 30],[1, 4, 6 ,7, 8, 17, 27],[11,15,18,21,26,35,37],[1, 10, 13, 16, 21, 22, 26]]), columns=list('ABCDEFG'))
df

A   B   C   D   E   F   G
0    5   6   8  13  19  20  24
1    2   5  10  22  24  31  37
2    7  13  14  19  21  28  31
3   11  15  18  23  27  28  33
4    1   2   5  10  13  26  34
..  ..  ..  ..  ..  ..  ..  ..
92   5   9  12  15  23  33  36
93   6  11  12  21  23  26  30
94   1   4   6   7   8  17  27
95  11  15  18  21  26  35  37
96   1  10  13  16  21  22  26

[97 rows x 7 columns]

In [12]:
df = df.iloc[::-1]
df

A   B   C   D   E   F   G
96   1  10  13  16  21  22  26
95  11  15  18  21  26  35  37
94   1   4   6   7   8  17  27
93   6  11  12  21  23  26  30
92   5   9  12  15  23  33  36
..  ..  ..  ..  ..  ..  ..  ..
4    1   2   5  10  13  26  34
3   11  15  18  23  27  28  33
2    7  13  14  19  21  28  31
1    2   5  10  22  24  31  37
0    5   6   8  13  19  20  24

[97 rows x 7 columns]

In [13]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data = transformed_dataset, index = df.index)

transformed_df


0         1         2         3         4         5         6
96 -1.052076  0.090165 -0.218883 -0.474442 -0.380280 -1.237087 -1.868449
95  1.751533  1.240961  0.821885  0.488338  0.600762  1.466495  1.041967
94 -1.052076 -1.290789 -1.675958 -2.207444 -2.930989 -2.276926 -1.603866
93  0.349729  0.320325 -0.427037  0.488338  0.012137 -0.405216 -0.810116
92  0.069368 -0.139994 -0.427037 -0.666998  0.012137  1.050559  0.777384
..       ...       ...       ...       ...       ...       ...       ...
4  -1.052076 -1.751108 -1.884111 -1.629777 -1.949947 -0.405216  0.248217
3   1.751533  1.240961  0.821885  0.873449  0.796970  0.010720 -0.016366
2   0.630089  0.780643 -0.010730  0.103226 -0.380280  0.010720 -0.545533
1  -0.771715 -1.060630 -0.843344  0.680893  0.208345  0.634624  1.041967
0   0.069368 -0.830471 -1.259651 -1.052109 -0.772697 -1.653023 -2.397616

[97 rows x 7 columns]

In [14]:
number_of_rows = df.values.shape[0]
window_length = 10
number_of_features = df.values.shape[1]

In [15]:
train = np.empty([number_of_rows-window_length,window_length,number_of_features],dtype=float)

label = np.empty([number_of_rows-window_length,number_of_features],dtype=float)

window_length = 10

for i in range(0,number_of_rows-window_length):
  train[i] = transformed_df.iloc[i:i+window_length, 0:number_of_features]
  label[i] = transformed_df.iloc[i+window_length: i+window_length+1, 0: number_of_features]

In [16]:
train.shape

(87, 10, 7)

In [17]:
label.shape

(87, 7)

In [18]:
train[0]

array([[-1.05207585,  0.09016544, -0.21888311, -0.47444175, -0.38028018,
        -1.23708705, -1.86844898],
       [ 1.75153287,  1.24096119,  0.82188463,  0.48833753,  0.60076178,
         1.46649488,  1.04196717],
       [-1.05207585, -1.29078946, -1.67595795, -2.20744444, -2.93098928,
        -2.27692626, -1.60386569],
       [ 0.34972851,  0.32032459, -0.42703666,  0.48833753,  0.0121366 ,
        -0.40521569, -0.81011583],
       [ 0.06936764, -0.13999371, -0.42703666, -0.6669976 ,  0.0121366 ,
         1.0505592 ,  0.77738388],
       [-1.05207585, -1.29078946, -1.67595795, -1.43722102, -2.14615572,
         0.01071999, -0.28094926],
       [-1.05207585, -0.37015286, -0.21888311,  0.29578167, -0.18407179,
         0.21868783, -0.81011583],
       [-1.05207585, -0.37015286, -0.84334376, -0.47444175,  0.0121366 ,
        -0.40521569, -0.01636598],
       [ 0.91045026,  0.55048374, -0.21888311, -0.85955346, -1.36132215,
        -0.19724785, -0.54553255],
       [ 0.34972851,  0.3203

In [19]:
train[1]

array([[ 1.75153287,  1.24096119,  0.82188463,  0.48833753,  0.60076178,
         1.46649488,  1.04196717],
       [-1.05207585, -1.29078946, -1.67595795, -2.20744444, -2.93098928,
        -2.27692626, -1.60386569],
       [ 0.34972851,  0.32032459, -0.42703666,  0.48833753,  0.0121366 ,
        -0.40521569, -0.81011583],
       [ 0.06936764, -0.13999371, -0.42703666, -0.6669976 ,  0.0121366 ,
         1.0505592 ,  0.77738388],
       [-1.05207585, -1.29078946, -1.67595795, -1.43722102, -2.14615572,
         0.01071999, -0.28094926],
       [-1.05207585, -0.37015286, -0.21888311,  0.29578167, -0.18407179,
         0.21868783, -0.81011583],
       [-1.05207585, -0.37015286, -0.84334376, -0.47444175,  0.0121366 ,
        -0.40521569, -0.01636598],
       [ 0.91045026,  0.55048374, -0.21888311, -0.85955346, -1.36132215,
        -0.19724785, -0.54553255],
       [ 0.34972851,  0.32032459, -0.42703666, -0.47444175, -0.77269697,
        -1.02911921,  0.5128006 ],
       [-0.21099323, -0.8304

In [20]:
label[0]

array([-0.21099323, -0.83047116, -1.4678044 , -1.43722102, -0.77269697,
       -1.02911921,  0.77738388])

In [21]:
label[1]

array([-1.05207585, -0.60031201,  0.19742398, -0.28188589, -0.77269697,
       -1.23708705,  0.24821731])

In [22]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
from keras.optimizers import SGD

batch_size = 64

In [51]:
import tensorflow as tf

model = Sequential()
model.add(Bidirectional(LSTM(21, activation="relu",
                             input_shape=(window_length,number_of_features),
                             return_sequences = True)))
model.add(Dropout(0.20))
model.add(Bidirectional(LSTM(21, activation="relu",
                             return_sequences = False)))
model.add(Dropout(0.20))
model.add(Dense(number_of_features))
epochs = 1000
learning_rate = 0.01
decay_rate = 0.001
momentum = 0.8
sgd = tf.keras.optimizers.legacy.SGD(
    learning_rate=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False
)
model.compile(loss = 'mse',optimizer = sgd, metrics = ['accuracy'])

In [55]:
model.fit(train,label,batch_size=64,epochs=epochs,verbose=1)

Epoch 1/1000
2/2 [==============================] - 0s 12ms/step - loss: 0.8097 - accuracy: 0.2184
Epoch 2/1000
2/2 [==============================] - 0s 13ms/step - loss: 0.7892 - accuracy: 0.1954
Epoch 3/1000
2/2 [==============================] - 0s 13ms/step - loss: 0.7374 - accuracy: 0.2414
Epoch 4/1000
2/2 [==============================] - 0s 13ms/step - loss: 0.7607 - accuracy: 0.2414
Epoch 5/1000
2/2 [==============================] - 0s 13ms/step - loss: 0.7476 - accuracy: 0.1494
Epoch 6/1000
2/2 [==============================] - 0s 12ms/step - loss: 0.7561 - accuracy: 0.2069
Epoch 7/1000
2/2 [==============================] - 0s 14ms/step - loss: 0.7884 - accuracy: 0.2184
Epoch 8/1000
2/2 [==============================] - 0s 13ms/step - loss: 0.7096 - accuracy: 0.2299
Epoch 9/1000
2/2 [==============================] - 0s 11ms/step - loss: 0.7432 - accuracy: 0.2644
Epoch 10/1000
2/2 [==============================] - 0s 13ms/step - loss: 0.7686 - accuracy: 0.2759
Epoch 11/

In [53]:
to_predict = np.array([[6, 11, 12, 21, 23, 26, 30],[1, 4, 6 ,7, 8, 17, 27],[11,15,18,21,26,35,37],[1, 10, 13, 16, 21, 22, 26],[5, 9, 12, 15, 23, 33, 36]])
scaled_to_predict = scaler.transform(to_predict)

In [54]:
scaled_predicted_output = model.predict(np.array([scaled_to_predict]))
print(scaler.inverse_transform(scaled_predicted_output).astype(int)[0])

1/1 [==============================] - 1s 571ms/step
[ 5  9 15 19 24 29 34]
